version: '3'
services:
  next-automation:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - .env
  # mongo:
  #   image: mongo:4.4
  #   ports:
  #     - "27017:27017"